import Head from 'next/head'

const PageHead = () => {
    return (
        <Head>
            <title>GO Shopping</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
        </Head>
    )
}

export default PageHead