import Head from 'next/head'

const PageHead = () => {
    return (
        <Head>
            <title>GO Shopping</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
    )
}

export default PageHead